ITEM.name = "Спинной нейромодуль Сан'Девистан"
ITEM.description = "Военный имплант, разработанный для спецподразделения [ДАННЫЕ УДАЛЕНЫ]. Ускоряет передачу нервных импульсов и реакции до сверхчеловеческих значений."
ITEM.category = "Implants"
ITEM.model = "models/mass_effect_3/weapons/misc/ammobox1 small.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.bonus = 57
ITEM.attrboost = "ref"
ITEM.skillbonus = 62
ITEM.skillname = "evasion"
ITEM.basechance = 120
ITEM.bodypart = "Нервная система"