ITEM.name = "Барьерный костюм \"Militech - EXO\""
ITEM.description = "Был создан специально для того чтобы уберечь полевых нетраннеров от физических повреждений. Надежен, эффективен, в нем даже можно пережить ядерный взрыв... Наверное?"
ITEM.model = "models/mass_effect_3/weapons/misc/armor case.mdl"
ITEM.width = 2
ITEM.height = 2
ITEM.price = 5000
ITEM.armorclass = 5 -- Класс брони, который должен устанавливаться через SetData()
ITEM.attributeCheckName = "phy" -- Название атрибута на который будет делаться проверка
ITEM.attributeCheckValue = 1 -- Значение, ниже которого персонаж сможет надевать бронежилет (то есть все у кого атрибут phy < 20, могу надевать бронежилет) 
ITEM.category = "Armor"
ITEM.outfitCategory = "Chest"