ITEM.name = "Бронежилет \"Militech - STEELROCK\""
ITEM.description = "Действительно надежный бронежилет, который способен защитить оболочку от оружия большого калибра."
ITEM.model = "models/mass_effect_3/weapons/misc/ammobox1 small.mdl"
ITEM.width = 2
ITEM.height = 2
ITEM.price = 750
ITEM.armorclass = 3 -- Класс брони, который должен устанавливаться через SetData()
ITEM.attributeCheckName = "phy" -- Название атрибута на который будет делаться проверка
ITEM.attributeCheckValue = 10 -- Значение, ниже которого персонаж сможет надевать бронежилет (то есть все у кого атрибут phy < 20, могу надевать бронежилет) 
ITEM.category = "Armor"
ITEM.outfitCategory = "Chest"