ITEM.name = "Бронированная нагрудная пластина \"Militech - KING\""
ITEM.description = "Очень надежная и мощная броня, способная выдержать выстрел противобункерного снаряда."
ITEM.model = "models/mass_effect_3/weapons/misc/armor case smaller.mdl"
ITEM.width = 2
ITEM.height = 2
ITEM.price = 1250
ITEM.armorclass = 4 -- Класс брони, который должен устанавливаться через SetData()
ITEM.attributeCheckName = "phy" -- Название атрибута на который будет делаться проверка
ITEM.attributeCheckValue = 5 -- Значение, ниже которого персонаж сможет надевать бронежилет (то есть все у кого атрибут phy < 20, могу надевать бронежилет) 
ITEM.category = "Armor"
ITEM.outfitCategory = "Chest"