ITEM.name = "Бронежилет \"Militech - MILVEST\""
ITEM.description = "Такие бронежилеты часто использует постовая служба и те кому они положены по уставу."
ITEM.model = "models/mass_effect_3/weapons/misc/armor case smaller.mdl"
ITEM.width = 2
ITEM.height = 2
ITEM.price = 6200
ITEM.armorclass = 2 -- Класс брони, который должен устанавливаться через SetData()
ITEM.attributeCheckName = "phy" -- Название атрибута на который будет делаться проверка
ITEM.attributeCheckValue = 15 -- Значение, ниже которого персонаж сможет надевать бронежилет (то есть все у кого атрибут phy < 20, могу надевать бронежилет) 
ITEM.category = "Armor"
ITEM.outfitCategory = "Chest"