ITEM.name = "Пилюли админа"
ITEM.model = "models/props_junk/garbage_metalcan001a.mdl"
ITEM.description = "Лечат нахуй от всего, абсолютно, хоть от спидорака."
ITEM.width = 1
ITEM.height = 1
ITEM.adminPills = true
ITEM.category = "Medicine"
ITEM.useSound = "items/medshot4.wav"
ITEM.price = 80085
ITEM.chance = 0