ITEM.name = "Таблетки для глаз \"Orihiro\""
ITEM.model = "models/props_junk/garbage_metalcan001a.mdl"
ITEM.description = "На упаковке множество надписей на японском языке. Единственное что вы можете прочесть это \"Применяется для улучшения зрения, профилактики возникновения и прогрессирования заболеваний глаз.\""
ITEM.width = 1
ITEM.height = 1
ITEM.category = "Medicine"
ITEM.useSound = "items/medshot4.wav"
ITEM.healing = "blindness"
ITEM.price = 1000